CREATE TABLE IF NOT EXISTS rapports_hemodialyse (
    id_rapport INT AUTO_INCREMENT PRIMARY KEY,
    id_medecin INT NOT NULL,
    antenne VARCHAR(50) NOT NULL,
    date_rapport DATE NOT NULL,
    femmes_3_12 INT NOT NULL DEFAULT 0,
    femmes_13_19 INT NOT NULL DEFAULT 0,
    femmes_20_49 INT NOT NULL DEFAULT 0,
    femmes_50_plus INT NOT NULL DEFAULT 0,
    hommes_3_12 INT NOT NULL DEFAULT 0,
    hommes_13_19 INT NOT NULL DEFAULT 0,
    hommes_20_49 INT NOT NULL DEFAULT 0,
    hommes_50_plus INT NOT NULL DEFAULT 0,
    total_patients_dialyses INT NOT NULL DEFAULT 0,
    nb_generateurs_fonctionnels INT NOT NULL DEFAULT 0,
    nb_postes_dialyse INT NOT NULL DEFAULT 0,
    nb_seances_urgence INT NOT NULL DEFAULT 0,
    nb_patients_sejour INT NOT NULL DEFAULT 0,
    nb_deces INT NOT NULL DEFAULT 0,
    statut ENUM('en_attente', 'valide', 'rejete') NOT NULL DEFAULT 'en_attente',
    commentaire_admin TEXT,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_medecin) REFERENCES medecins(id_medecin) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 